os:
- linux
- osx

language: nix

sudo: required

git:
  depth: 1

env:
  global:
  - secure: ChuyBaHm/mf4iCFHg284Lxh58npRf+DCdq2nIn5WFp5DYGZXhddsxZwEriMdjWqPazBLbFan/eZHjf7Z/MdgTyoA8tE8BRj58rZg5UIgCwHCguF0UeZxvvSJyHQ3XHEw77xOKgo5xuXpU9SjOA15+0A/qXHnrC5w1u7Gao4D8BzFKTP5/QcbL2tyGh+lO/7CqjrryL8pCrlZdne02/i9pnFV264ww9gNgBfUIFa++fJgHHLyrArHx46KX+kii/YOlypY761kaW5wfppAC+J60U6d70ZnWbKGiQsiXxTt6UaGDPw4JLEIrpDfKLhakgaeHJuK/6EbB8Kjs2kyXJn3/x851welK7JP9whS+Fb3wvf6qw4EV62OZlvELFZwAJX7kIePAAsMznGpojJgcj0yVlO7TCnlyJe1aMewlXhaZsQDHAZjrWcqRzrjwX04mzlVs0cmaTAvUwKxkvvVXRZGQaoROTMynAfVCxkS6VO+st3iLrWTD+P6VY3dzPEn4MEhBmVpOaRdBX6G2jGSzl2ZyXKyspI5clRLSuMYNjJsht3cO95L8l20QNPIkw3ro8TaqOBKKPbcxFxrllF5cSQC3F1tMf1wVCvOkwQgVbejRN2WP3fpY8858BQhYL+eonJUcKqpdZ9O0v4vxOPmnKoIFehVlaxJDUWqsiXJPD7CcGA=
  matrix:
  - COQVERSION=coq_8_6
  - COQVERSION=coq_8_7
  - COQVERSION=coq_8_8

install:
- nix-shell --argstr compiler coq_8_6 --run true
- nix-shell --argstr compiler coq_8_7 --run true
- nix-shell --argstr compiler coq_8_8 --run true

matrix:
  allow_failures:
  - env: COQVERSION=coq_8_8

script:
- nix-env -iA cachix -f https://github.com/NixOS/nixpkgs/tarball/db557aab7b690f5e0e3348459f2e4dc8fd0d9298
- cachix use refine-freer
- if [ ! -v $CACHIX_SIGNING_KEY ]; then cachix push refine-freer --watch-store& fi
- if [ ! -v $CACHIX_SIGNING_KEY ]; then nix-build --argstr compiler $COQVERSION | cachix push refine-freer; else ./build.sh; fi

branches:
  only:
  - master
